config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :user_answers, only: [:update]

  resources :questions, only: [] do
    get :random, on: :collection
    resources :user_answers, only: [:create]
  end

  resources :questionnaires do
    resources :questions do
      resources :answers
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id                    :uuid             not null, primary key
#  answer_type           :integer          not null
#  name                  :string           not null
#  position              :integer
#  question_source_type  :integer          not null
#  question_source_value :string           not null
#  required              :boolean          default(FALSE), not null
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  questionnaire_id      :uuid             not null
#
# Indexes
#
#  index_questions_on_questionnaire_id  (questionnaire_id)
#
# Foreign Keys
#
#  fk_rails_...  (questionnaire_id => questionnaires.id)
#
class Question < ApplicationRecord
  belongs_to :questionnaire
  has_many :answers, dependent: :destroy
  has_many :user_answers, dependent: :destroy

  enum answer_type: { single_choice: 0 }
  #enum answer_type: { single_choice: 0, multiple_choice: 1, long_answer: 2 }

  enum question_source_type: { gdrive_video: 0, gdrive_image: 1 }

  validates :answer_type, :name, :question_source_type, :question_source_value, :questionnaire_id, presence: true

  def self.question_source_type_select
    question_source_types.keys.map { |k| [Question.human_enum_name(:question_source_type, k), k] }
  end

  def self.answer_type_select
    answer_types.keys.map { |k| [Question.human_enum_name(:answer_type, k), k] }
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_questionnaire, only: %i[ index new show create edit update destroy ]
  before_action :set_question, only: %i[ show edit update destroy ]
  skip_before_action :authenticate_user!, only: :random

  # GET /questions or /questions.json
  def index
    @questions = @questionnaire.questions.order(position: :asc)
  end

  def random
    if params[:question_id]
      @question = Question.find(params[:question_id])
    else
      @question = Question.all.sample
    end
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = @questionnaire.questions.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @question = @questionnaire.questions.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to [@questionnaire, @question], notice: "Question was successfully created." }
        format.json { render :show, status: :created, location: [@questionnaire, @question] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to [@questionnaire, @question], notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: [@questionnaire, @question] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy

    respond_to do |format|
      format.html { redirect_to questionnaire_questions_url(@questionnaire), notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:questionnaire_id])
    end

    def set_question
      @question = @questionnaire.questions.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:name, :position, :question_source_type, :required, :question_source_value, :answer_type, :questionnaire_id)
    end
end

app/views/questions/_form.html.erb
<%= form_with(model: [@questionnaire, question]) do |form| %>
      <div class='field is-horizontal'>
        <div class='field-label is-normal'>
          <%= form.label :name, class: 'label' %>
        </div>
        <div class='field-body'>
          <div class='field'>
            <div class='control'>
              <% input_class = question.errors[:name].present? ? 'input is-danger' : 'input' %>
              <%= form.text_field :name, class: input_class %>
              <%= content_tag :p, question.errors[:name].to_sentence, class: "help is-danger" %>
            </div>
          </div>
        </div>
      </div>

      <div class='field is-horizontal'>
        <div class='field-label is-normal'>
          <%= form.label :position, class: 'label' %>
        </div>
        <div class='field-body'>
          <div class='field'>
            <div class='control'>
              <% input_class = question.errors[:position].present? ? 'input is-danger' : 'input' %>
              <%= form.number_field :position, class: input_class %>
              <%= content_tag :p, question.errors[:position].to_sentence, class: "help is-danger" %>
            </div>
          </div>
        </div>
      </div>

  <div class='field is-horizontal'>
    <div class='field-label is-normal'>
      <%= form.label :question_source_value, class: 'label' %>
    </div>
    <div class='field-body'>
      <div class='field'>
        <div class='control'>
          <% input_class = question.errors[:question_source_value].present? ? 'input is-danger' : 'input' %>
          <%= form.text_field :question_source_value, class: input_class %>
          <%= content_tag :p, question.errors[:question_source_value].to_sentence, class: "help is-danger" %>
        </div>
      </div>
    </div>
  </div>

  <div class='field is-horizontal'>
    <div class='field-label is-normal'>
      <%= form.label :question_source_type, class: 'label' %>
    </div>
    <div class='field-body'>
      <div class='field'>
        <div class='control'>
          <% input_class = question.errors[:question_source_type].present? ? 'input is-danger' : 'input' %>
          <%= form.select :question_source_type,
            options_for_select(Question.question_source_type_select, selected: form.object.question_source_type),
            class: input_class
          %>
          <%= content_tag :p, question.errors[:question_source_type].to_sentence, class: "help is-danger" %>
        </div>
      </div>
    </div>
  </div>

  <% if false %>
    <div class='field is-horizontal'>
      <div class='field-label is-normal'>
        <%= form.label :required, class: 'label' %>
      </div>
      <div class='field-body'>
        <div class='field'>
          <div class='control'>
            <% input_class = question.errors[:required].present? ? 'check is-danger' : 'check' %>
            <%= form.check_box :required, class: input_class %>
            <%= content_tag :p, question.errors[:required].to_sentence, class: "help is-danger" %>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <div class='field is-horizontal'>
    <div class='field-label is-normal'>
      <%= form.label :answer_type, class: 'label' %>
    </div>
    <div class='field-body'>
      <div class='field'>
        <div class='control'>
          <% input_class = question.errors[:answer_type].present? ? 'input is-danger' : 'input' %>
          <%= form.select :answer_type,
            options_for_select(Question.answer_type_select, selected: form.object.answer_type),
            class: input_class
          %>
          <%= content_tag :p, question.errors[:answer_type].to_sentence, class: "help is-danger" %>
        </div>
      </div>
    </div>
  </div>

  <hr>
  <div class="field is-horizontal">
    <div class="field-label is-normal"></div>
    <div class="field-body">
      <div class="field">
        <div class="field-body">
          <div class="field is-grouped">
            <div class="control">
              <%= form.submit class: 'button is-success' %>
              <% if show_back %>
                <%= link_to I18n.t('.back'), questionnaire_questions_path, class: 'button is-light' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">
  <p>
    <strong>Name:</strong>
    <%= question.name %>
  </p>

  <p>
    <strong>Position:</strong>
    <%= question.position %>
  </p>

  <p>
    <strong>Question source type:</strong>
    <%= question.question_source_type %>
  </p>

  <p>
    <strong>Required:</strong>
    <%= question.required %>
  </p>

  <p>
    <strong>Question source value:</strong>
    <%= question.question_source_value %>
  </p>

  <p>
    <strong>Answer type:</strong>
    <%= question.answer_type %>
  </p>

  <p>
    <strong>Questionnaire:</strong>
    <%= question.questionnaire_id %>
  </p>

</div>

app/views/questions/_small_table.html.erb
<div class='table-wrapper'>
  <table class='table is-striped is-hoverable is-fullwidth'>
    <thead>
      <tr>
        <th><%= Question.human_attribute_name(:name) %></th>
        <th><%= Question.human_attribute_name(:question_source_type) %></th>
        <th><%= Question.human_attribute_name(:answer_type) %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% questions.each do |question| %>
        <tr>
            <td><%= question.name %></td>
            <td><%= question.question_source_type %></td>
            <td><%= question.answer_type %></td>
            <td>
            <div class='buttons is-right'>
              <%= link_to [@questionnaire, question], class: 'button is-small is-primary' do %>
                <span class="icon is-small"><i class="fas fa-newspaper"></i></span>
              <% end %>
              <%= link_to edit_questionnaire_question_path(@questionnaire, question), class: 'button is-small is-info' do %>
                <span class="icon is-small"><i class="fas fa-pen-to-square"></i></span>
              <% end %>
              <%= link_to [@questionnaire, question], method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'button is-danger is-small' do %>
                <span class="icon is-small"><i class="fas fa-trash-can"></i></span>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/questions/_table.html.erb
<div class='table-wrapper'>
  <table class='table is-striped is-hoverable is-fullwidth'>
    <thead>
      <tr>
        <th><%= Question.human_attribute_name(:name) %></th>
        <th><%= Question.human_attribute_name(:question_source_type) %></th>
        <th><%= Question.human_attribute_name(:answer_type) %></th>
        <th><%= Question.human_attribute_name(:questionnaire) %></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% questions.each do |question| %>
        <tr>
            <td><%= question.name %></td>
            <td><%= question.question_source_type %></td>
            <td><%= question.answer_type %></td>
            <td><%= link_to question.questionnaire.name, question.questionnaire %></td>
            <td>
            <div class='buttons is-right'>
              <%= link_to [@questionnaire, question], class: 'button is-small is-primary' do %>
                <span class="icon is-small"><i class="fas fa-newspaper"></i></span>
              <% end %>
              <%= link_to edit_questionnaire_question_path(@questionnaire, question), class: 'button is-small is-info' do %>
                <span class="icon is-small"><i class="fas fa-pen-to-square"></i></span>
              <% end %>
              <%= link_to [@questionnaire, question], method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'button is-danger is-small' do %>
                <span class="icon is-small"><i class="fas fa-trash-can"></i></span>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/questions/edit.html.erb
<section class='section'>
  <div class="is-title-bar">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <h1 class="title">Question</h1>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
        </div>
      </div>
    </div>
  </div>
  <div class='card has-table'>
    <div class='card-content'>
      <%= render 'form', question: @question, show_back: true %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<section class='section'>
  <div class="is-title-bar">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <h1 class="title">Question</h1>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
          <%= link_to 'Dodaj Question', new_questionnaire_question_path, class: "button is-primary" %>
        </div>
      </div>
    </div>
  </div>
  <div class='card has-table'>
    <div class='card-content'>
      <%= render 'table', questions: @questions, show_back: true %>
    </div>
  </div>
</section>

app/views/questions/new.html.erb
<section class='section'>
  <div class="is-title-bar">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <h1 class="title">Question</h1>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
        </div>
      </div>
    </div>
  </div>
  <div class='card has-table'>
    <div class='card-content'>
      <%= render 'form', question: @question, show_back: true %>
    </div>
  </div>
</div>

app/views/questions/random.html.erb
<section class='section'>
  <div class="columns">
    <div class="column">
      <div class='box'>
        <% if @question.gdrive_video? %>
          <iframe src="<%= @question.question_source_value %>" allow="autoplay"></iframe>
        <% end %>
        <% if @question.gdrive_image? %>
          <iframe src="<%= @question.question_source_value %>" allow="autoplay"></iframe>
        <% end %>
      </div>
    </div>
    <div class="column">
      <% if user_signed_in? %>
        <div class='box'>
          <h2><b><%= @question.name %></b></h2>
          <% case @question.answer_type %>
          <% when 'single_choice' %>
            <% if UserAnswer.exists?(question_id: @question.id, user_id: current_user.id) %>
              Your answer:
              <% answer = UserAnswer.find_by(question_id: @question.id, user_id: current_user.id).answer %>
              <br>
              <% if answer.correct %>
                <span class="icon has-text-success">
                  <i class="fas fa-check-square"></i>
                </span>
                <%= answer.name %>
              <% else %>
                <span class="icon has-text-danger">
                  <i class="fas fa-check-square"></i>
                </span>
                <%= answer.name %>
                <hr>
                Correct answer:
                <br>
                <% @question.answers.each do |answer| %>
                  <% if answer.correct %>
                    <span class="icon has-text-success">
                      <i class="fas fa-check-square"></i>
                    </span>
                    <%= answer.name %>
                  <% else %>
                    <span class="icon has-text-danger">
                      <i class="fas fa-check-square"></i>
                    </span>
                    <%= answer.name %>
                  <% end %>
                  <br>
                <% end %>
              <% end %>
            <% else %>
              <%= form_with(model: [@question, @question.user_answers.new]) do |form| %>
                <%= form.hidden_field :user_id, value: current_user.id %>
                <%= form.collection_radio_buttons(:answer_id, @question.answers, :id, :name, {}, {onchange: 'this.form.submit()'}) do |b| %>
                  <%= b.label(:"data-value" => b.value) { b.radio_button + " " + b.text } %>
                  <br>
                <% end %>
              <% end %>
            <% end %>
          <% when 'long_answer' %>
          <% when 'multiple_choice' %>
          <% end %>
        </div>
      <% else %>
        <div class='box'>
          <h2>If you want to know the answer sign in!</h2>
          <br>
          <% @question.answers.each do |answer| %>
            <span class="icon has-text-info">
              <i class="fas fa-question-circle"></i>
            </span>
            <%= answer.name %>
            <br>
          <% end %>
        </div>
      <% end %>
      <div class='box'>
        <%= link_to 'Next random question', random_questions_path, class: 'button is-info is-fullwidth' %>
      </div>
    </div>
  </div>
</section>

app/views/questions/show.html.erb
<section class='section'>
  <div class="columns">
    <div class="column">
            <p>
        <strong><%= Question.human_attribute_name(:name) %>:</strong>
              <%= @question.name %>
            </p>

            <% if @question.position %>
              <p>
                <strong><%= Question.human_attribute_name(:position) %>:</strong>
                <%= @question.position %>
              </p>
            <% end %>

            <p>
        <strong><%= Question.human_attribute_name(:question_source_type) %>:</strong>
              <%= @question.question_source_type %>
            </p>

            <p>
        <strong><%= Question.human_attribute_name(:question_source_value) %>:</strong>
              <%= @question.question_source_value %>
            </p>

            <p>
        <strong><%= Question.human_attribute_name(:answer_type) %>:</strong>
              <%= @question.answer_type %>
            </p>

            <p>
        <strong><%= Question.human_attribute_name(:questionnaire) %>:</strong>
              <%= link_to @question.questionnaire.name, @question.questionnaire %>
            </p>


      <hr>

      <div class='buttons'>
        <%= link_to I18n.t('.edit'), edit_questionnaire_question_path(@questionnaire, @question), class: 'button is-primary' %>
        <%= link_to I18n.t('.back'), questionnaire_questions_path, class: 'button is-light' %>
      </div>
    </div>
    <div class="column">
      <div class='content'>
        <ul>
          <% @question.answers.each do |answer| %>
            <% if answer.correct %>
              <li>
                <%= answer.name %>
                <span class="icon has-text-success">
                  <i class="fas fa-check-square"></i>
                </span>
              </li>
            <% else %>
              <li>
                <%= answer.name %>
                <span class="icon has-text-danger">
                  <i class="fas fa-check-square"></i>
                </span>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <%= render 'answers/form', answer: @question.answers.new, show_back: false %>
    </div>
  </div>
</section>