config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :user_answers, only: [:update]

  resources :questions, only: [] do
    get :random, on: :collection
    resources :user_answers, only: [:create]
  end

  resources :questionnaires do
    resources :questions do
      resources :answers
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :uuid             not null, primary key
#  correct     :boolean          default(FALSE), not null
#  description :text
#  name        :string           not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  question_id :uuid             not null
#
# Indexes
#
#  index_answers_on_question_id  (question_id)
#
# Foreign Keys
#
#  fk_rails_...  (question_id => questions.id)
#
class Answer < ApplicationRecord
  belongs_to :question

  validates :name, presence: true
  validates :name, uniqueness: { scope: :question_id }

  validate :only_answer_correct_in_single_choice

  def only_answer_correct_in_single_choice
    if correct && question.single_choice?
      if question.answers.except(self).any? {|answer| answer.correct? }
        errors.add(:correct, "can be only one correct answer")
      end
    end
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_questionnaire
  before_action :set_question
  before_action :set_answer, only: %i[ show edit update destroy ]

  # GET /answers or /answers.json
  def index
    @answers = @question.answers.all
  end

  # GET /answers/1 or /answers/1.json
  def show
  end

  # GET /answers/new
  def new
    @answer = @question.answers.new
  end

  # GET /answers/1/edit
  def edit
  end

  # POST /answers or /answers.json
  def create
    @answer = @question.answers.new(answer_params)

    respond_to do |format|
      if @answer.save
        format.html { redirect_to [@questionnaire, @question], notice: "Answer was successfully created." }
        format.json { render :show, status: :created, location: [@questionnaire, @question, @answer] }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /answers/1 or /answers/1.json
  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to [@questionnaire, @question, @answer], notice: "Answer was successfully updated." }
        format.json { render :show, status: :ok, location: [@questionnaire, @question, @answer] }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /answers/1 or /answers/1.json
  def destroy
    @answer.destroy

    respond_to do |format|
      format.html { redirect_to questionnaire_question_answers_url(questionnaire_id: @questionnaire.id, question_id: @question.id), notice: "Answer was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:questionnaire_id])
    end

    def set_question
      @question = @questionnaire.questions.find(params[:question_id])
    end

    def set_answer
      @answer = @question.answers.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def answer_params
      params.require(:answer).permit(:correct, :name, :question_id)
    end
end

app/views/answers/_answer.html.erb
<div id="<%= dom_id answer %>">
  <p>
    <strong>Correct:</strong>
    <%= answer.correct %>
  </p>

  <p>
    <strong>Name:</strong>
    <%= answer.name %>
  </p>

  <p>
    <strong>Question:</strong>
    <%= answer.question_id %>
  </p>

</div>

app/views/answers/_form.html.erb
<%= form_with(model: [@questionnaire, @question, answer]) do |form| %>
  <div class='field is-horizontal'>
    <div class='field-label is-normal'>
      <%= form.label :name, class: 'label' %>
    </div>
    <div class='field-body'>
      <div class='field'>
        <div class='control'>
          <% input_class = answer.errors[:name].present? ? 'input is-danger' : 'input' %>
          <%= form.text_field :name, class: input_class %>
          <%= content_tag :p, answer.errors[:name].to_sentence, class: "help is-danger" %>
        </div>
      </div>
    </div>
  </div>

  <div class='field is-horizontal'>
    <div class='field-label is-normal'>
      <%= form.label :correct, class: 'label' %>
    </div>
    <div class='field-body'>
      <div class='field'>
        <div class='control'>
          <% input_class = answer.errors[:correct].present? ? 'input is-danger' : 'input' %>
          <%= form.label :correct, class: 'checkbox' do %>
            <%= form.check_box :correct %>
          <% end %>
          <%= content_tag :p, answer.errors[:correct].to_sentence, class: "help is-danger" %>
        </div>
      </div>
    </div>
  </div>
  <div class="field is-horizontal">
    <div class="field-label is-normal"></div>
    <div class="field-body">
      <div class="field">
        <div class="field-body">
          <div class="field is-grouped">
            <div class="control">
              <%= form.submit class: 'button is-success' %>
              <% if show_back %>
                <%= link_to I18n.t('.back'), [@questionnaire, @question], class: 'button is-light' %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/answers/edit.html.erb
<section class='section'>
  <div class="is-title-bar">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <h1 class="title">Answer</h1>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
        </div>
      </div>
    </div>
  </div>
  <div class='card has-table'>
    <div class='card-content'>
      <%= render 'form', answer: @answer %>
    </div>
  </div>
</div>

app/views/answers/index.html.erb
<section class='section'>
  <div class="is-title-bar">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <h1 class="title">Answer</h1>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
          <%= link_to 'Add Answer', new_questionnaire_question_answer_path, class: "button is-primary" %>
        </div>
      </div>
    </div>
  </div>
  <div class='card has-table'>
    <div class='card-content'>
      <div class='table-wrapper'>
        <table class='table is-striped is-hoverable is-fullwidth'>
          <thead>
            <tr>
              <th><%= Answer.human_attribute_name(:correct) %></th>
              <th><%= Answer.human_attribute_name(:name) %></th>
              <th><%= Answer.human_attribute_name(:question) %></th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @answers.each do |answer| %>
              <tr>
                  <td><%= answer.correct %></td>
                  <td><%= answer.name %></td>
                  <td><%= answer.question_id %></td>
                  <td>
                  <div class='buttons is-right'>
                    <%= link_to [@questionnaire, @question, answer], class: 'button is-small is-primary' do %>
                      <span class="icon is-small"><i class="fas fa-newspaper"></i></span>
                    <% end %>
                    <%= link_to edit_questionnaire_question_answer_path(questionnaire_id: @questionnaire.id, question_id: @question.id, id: answer.id), class: 'button is-small is-info' do %>
                      <span class="icon is-small"><i class="fas fa-pen-to-square"></i></span>
                    <% end %>
                    <%= link_to [@questionnaire, @question, answer], method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'button is-danger is-small' do %>
                      <span class="icon is-small"><i class="fas fa-trash-can"></i></span>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/answers/new.html.erb
<section class='section'>
  <div class="is-title-bar">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <h1 class="title">Answer</h1>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
        </div>
      </div>
    </div>
  </div>
  <div class='card has-table'>
    <div class='card-content'>
      <%= render 'form', answer: @answer, show_back: true %>
    </div>
  </div>
</div>

app/views/answers/show.html.erb
<section class='section'>
  <div class='card has-table'>
    <div class='card-content'>
            <p>
        <strong><%= Answer.human_attribute_name(:correct) %>:</strong>
              <%= @answer.correct %>
            </p>

            <p>
        <strong><%= Answer.human_attribute_name(:name) %>:</strong>
              <%= @answer.name %>
            </p>

            <p>
        <strong><%= Answer.human_attribute_name(:question) %>:</strong>
              <%= @answer.question_id %>
            </p>

      
      <hr>

      <div class='buttons'>
        <%= link_to I18n.t('.edit'), edit_answer_path(@answer), class: 'button is-primary' %>
        <%= link_to I18n.t('.back'), answers_path, class: 'button is-light' %>
      </div>
    </div>
  </div>
</section>