config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :user_answers, only: [:update]

  resources :questions, only: [] do
    get :random, on: :collection
    resources :user_answers, only: [:create]
  end

  resources :questionnaires do
    resources :questions do
      resources :answers
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/questionnaire.rb
# == Schema Information
#
# Table name: questionnaires
#
#  id         :uuid             not null, primary key
#  name       :string           not null
#  state      :integer          default(NULL), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Questionnaire < ApplicationRecord
  enum state: { open: 1 }
  #enum state: [:draft, :open, :closed]

  has_many :questions, dependent: :destroy

  validates :name, presence: true

  def self.state_select
    states.keys.map { |k| [Questionnaire.human_enum_name(:state, k), k] }
  end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  before_action :set_questionnaire, only: %i[ show edit update destroy ]

  # GET /questionnaires or /questionnaires.json
  def index
    @questionnaires = Questionnaire.all
  end

  # GET /questionnaires/1 or /questionnaires/1.json
  def show
  end

  # GET /questionnaires/new
  def new
    @questionnaire = Questionnaire.new
  end

  # GET /questionnaires/1/edit
  def edit
  end

  # POST /questionnaires or /questionnaires.json
  def create
    @questionnaire = Questionnaire.new(questionnaire_params)

    respond_to do |format|
      if @questionnaire.save
        format.html { redirect_to questionnaire_url(@questionnaire), notice: "Questionnaire was successfully created." }
        format.json { render :show, status: :created, location: @questionnaire }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questionnaires/1 or /questionnaires/1.json
  def update
    respond_to do |format|
      if @questionnaire.update(questionnaire_params)
        format.html { redirect_to questionnaire_url(@questionnaire), notice: "Questionnaire was successfully updated." }
        format.json { render :show, status: :ok, location: @questionnaire }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questionnaires/1 or /questionnaires/1.json
  def destroy
    @questionnaire.destroy

    respond_to do |format|
      format.html { redirect_to questionnaires_url, notice: "Questionnaire was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_questionnaire
      @questionnaire = Questionnaire.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def questionnaire_params
      params.require(:questionnaire).permit(:name, :state)
    end
end

app/views/questionnaires/_form.html.erb
<%= form_with(model: questionnaire) do |form| %>
  <div class='field is-horizontal'>
    <div class='field-label is-normal'>
      <%= form.label :name, class: 'label' %>
    </div>
    <div class='field-body'>
      <div class='field'>
        <div class='control'>
          <% input_class = @questionnaire.errors[:name].present? ? 'input is-danger' : 'input' %>
          <%= form.text_field :name, class: input_class %>
          <%= content_tag :p, @questionnaire.errors[:name].to_sentence, class: "help is-danger" %>
        </div>
      </div>
    </div>
  </div>

  <div class='field is-horizontal'>
    <div class='field-label is-normal'>
      <%= form.label :state, class: 'label' %>
    </div>
    <div class='field-body'>
      <div class='field'>
        <div class='control'>
          <% input_class = @questionnaire.errors[:state].present? ? 'input is-danger' : 'input' %>
          <%= form.select :state,
            options_for_select(Questionnaire.state_select, selected: form.object.state),
            class: input_class
          %>
          <%= content_tag :p, @questionnaire.errors[:state].to_sentence, class: "help is-danger" %>
        </div>
      </div>
    </div>
  </div>

  <hr>
  <div class="field is-horizontal">
    <div class="field-label is-normal"></div>
    <div class="field-body">
      <div class="field">
        <div class="field-body">
          <div class="field is-grouped">
            <div class="control">
              <%= form.submit class: 'button is-success' %>
              <%= link_to I18n.t('.back'), questionnaires_path, class: 'button is-light' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/questionnaires/_questionnaire.html.erb
<div id="<%= dom_id questionnaire %>">
  <p>
    <strong>Name:</strong>
    <%= questionnaire.name %>
  </p>

  <p>
    <strong>State:</strong>
    <%= questionnaire.state %>
  </p>

</div>

app/views/questionnaires/edit.html.erb
<section class='section'>
  <div class="is-title-bar">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <h1 class="title">Questionnaire</h1>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
        </div>
      </div>
    </div>
  </div>
  <div class='card has-table'>
    <div class='card-content'>
      <%= render 'form', questionnaire: @questionnaire %>
    </div>
  </div>
</div>

app/views/questionnaires/index.html.erb
<section class='section'>
  <div class="is-title-bar">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <h1 class="title">Questionnaire</h1>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
          <%= link_to 'Dodaj Questionnaire', new_questionnaire_path, class: "button is-primary" %>
        </div>
      </div>
    </div>
  </div>
  <div class='card has-table'>
    <div class='card-content'>
      <div class='table-wrapper'>
        <table class='table is-striped is-hoverable is-fullwidth'>
          <thead>
            <tr>
              <th><%= Questionnaire.human_attribute_name(:name) %></th>
              <th><%= Questionnaire.human_attribute_name(:state) %></th>
              <th colspan="3"></th>
            </tr>
          </thead>

          <tbody>
            <% @questionnaires.each do |questionnaire| %>
              <tr>
                  <td><%= questionnaire.name %></td>
                  <td><%= questionnaire.state %></td>
                  <td>
                  <div class='buttons is-right'>
                    <%= link_to questionnaire, class: 'button is-small is-primary' do %>
                      <span class="icon is-small"><i class="fas fa-newspaper"></i></span>
                    <% end %>
                    <%= link_to edit_questionnaire_path(questionnaire), class: 'button is-small is-info' do %>
                      <span class="icon is-small"><i class="fas fa-pen-to-square"></i></span>
                    <% end %>
                    <%= link_to questionnaire, method: :delete, data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: 'button is-danger is-small' do %>
                      <span class="icon is-small"><i class="fas fa-trash-can"></i></span>
                    <% end %>
                  </div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>

app/views/questionnaires/new.html.erb
<section class='section'>
  <div class="is-title-bar">
    <div class="level">
      <div class="level-left">
        <div class="level-item">
          <h1 class="title">Questionnaire</h1>
        </div>
      </div>
      <div class="level-right">
        <div class="level-item">
        </div>
      </div>
    </div>
  </div>
  <div class='card has-table'>
    <div class='card-content'>
      <%= render 'form', questionnaire: @questionnaire %>
    </div>
  </div>
</div>

app/views/questionnaires/show.html.erb
<section class='section'>
  <div class='columns'>
    <div class='column'>
      <div class='card has-table'>
        <div class='card-content'>
                <p>
            <strong><%= Questionnaire.human_attribute_name(:name) %>:</strong>
                  <%= @questionnaire.name %>
                </p>

                <p>
            <strong><%= Questionnaire.human_attribute_name(:state) %>:</strong>
                  <%= @questionnaire.state %>
                </p>

          <hr>

          <div class='buttons'>
            <%= link_to I18n.t('.edit'), edit_questionnaire_path(@questionnaire), class: 'button is-primary' %>
            <%= link_to I18n.t('.back'), questionnaires_path, class: 'button is-light' %>
          </div>
        </div>
      </div>

      <div class='box'>
        <%= render 'questions/form', question: @questionnaire.questions.new, show_back: false %>
      </div>
    </div>
    <div class='column'>
      <div class='card has-table'>
        <div class='card-content'>
          <%= render 'questions/small_table', questions: @questionnaire.questions.order(position: :asc), show_back: false %>
        </div>
      </div>
    </div>
  </div>
</section>